"""create Stage 1 marketplace schema

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendors",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("whatsapp_number", sa.String(length=20), nullable=False),
        sa.Column("business_name", sa.String(length=120), nullable=True),
        sa.Column("paystack_public_key", sa.String(length=255), nullable=True),
        sa.Column("bank_account", sa.String(length=50), nullable=True),
        sa.Column(
            "greeting_message",
            sa.Text(),
            server_default=sa.text("'Hey! Welcome to our shop!'"),
            nullable=True,
        ),
        sa.Column(
            "preferred_language",
            sa.String(length=20),
            server_default=sa.text("'pidgin'"),
            nullable=True,
        ),
        sa.Column("bot_number", sa.String(length=20), nullable=True),
        sa.Column("dashboard_url", sa.String(length=255), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "carts",
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("customer_phone", sa.String(length=20), nullable=False),
        sa.Column(
            "items",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.String(length=30),
            server_default=sa.text("'active'"),
            nullable=True,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vendor_id", "customer_phone"),
    )
    op.create_table(
        "conversations",
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("customer_phone", sa.String(length=20), nullable=False),
        sa.Column(
            "conversation_state",
            sa.String(length=30),
            server_default=sa.text("'browsing'"),
            nullable=True,
        ),
        sa.Column(
            "message_history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("language_detected", sa.String(length=20), nullable=True),
        sa.Column(
            "messages_this_session",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "last_touched",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vendor_id", "customer_phone"),
    )
    op.create_table(
        "orders",
        sa.Column("order_code", sa.String(length=20), nullable=True),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("customer_phone", sa.String(length=20), nullable=False),
        sa.Column("customer_name", sa.String(length=120), nullable=True),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default=sa.text("'new'"),
            nullable=True,
        ),
        sa.Column(
            "payment_status",
            sa.String(length=30),
            server_default=sa.text("'pending_payment'"),
            nullable=True,
        ),
        sa.Column("paystack_ref", sa.String(length=120), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_code"),
    )
    op.create_index("idx_orders_status", "orders", ["status"], unique=False)
    op.create_index("idx_orders_vendor_id", "orders", ["vendor_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("stock", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=True,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_products_vendor_id", "products", ["vendor_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_products_vendor_id", table_name="products")
    op.drop_table("products")
    op.drop_index("idx_orders_vendor_id", table_name="orders")
    op.drop_index("idx_orders_status", table_name="orders")
    op.drop_table("orders")
    op.drop_table("conversations")
    op.drop_table("carts")
    op.drop_table("vendors")
    # ### end Alembic commands ###
